### ISSUE TITLE
Postwoman won't build, produces 'FATAL Nuxt build error'

### ISSUE THREAD

**Issue by ragouel** [liyasthomas/postwoman#824]
Postwoman fails to build. 

**To Reproduce**
1. Download [1.9.5](https://github.com/liyasthomas/postwoman/archive/v1.9.5.tar.gz)
2. extract, cd into and execute:

  `npm install --cache "path-to-/npm-cache"`
  `npm run build --cache "path-to/npm-cache" `

 - OS: Arch Linux 4.20.13-arch1-1-ARCH
 - npm version 6.5.0 
- nodejs version 14.0.0
 - Version 1.9.5

 <pre><code>ERROR in ./.nuxt/client.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/.nuxt/client.js: Cannot find module '@babel/compat-data/corejs3-shipped-proposals'
Require stack:
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@babel/preset-env/lib/index.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@nuxt/babel-preset-app/src/index.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@babel/core/lib/config/files/plugins.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@babel/core/lib/config/files/index.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@babel/core/lib/index.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/babel-loader/lib/index.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/loader-runner/lib/loadLoader.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/loader-runner/lib/LoaderRunner.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/webpack/lib/NormalModule.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/webpack/lib/NormalModuleFactory.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/webpack/lib/Compiler.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/webpack/lib/webpack.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@nuxt/webpack/dist/webpack.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@nuxt/cli/dist/cli-index.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@nuxt/cli/dist/cli.js
- /home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/nuxt/bin/nuxt.js (While processing: "/home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@nuxt/babel-preset-app/src/index.js")
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:1014:15)
    at Function.Module._load (internal/modules/cjs/loader.js:884:27)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@babel/preset-env/lib/polyfills/corejs3/usage-plugin.js:10:55)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
    at Module.require (internal/modules/cjs/loader.js:1074:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/crow/Git/BROKEN/postwoman/src/postwoman-1.9.5/node_modules/@babel/preset-env/lib/index.js:29:44)
    at Module._compile (internal/modules/cjs/loader.js:1185:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1205:10)
    at Module.load (internal/modules/cjs/loader.js:1034:32)
    at Function.Module._load (internal/modules/cjs/loader.js:923:14)
 @ multi ./.nuxt/client.js app[0]

 FATAL  Nuxt build error </pre></code>

[2020-04-29T14_01_09_957Z-debug.log](https://github.com/liyasthomas/postwoman/files/4552160/2020-04-29T14_01_09_957Z-debug.log)

**Comment by liyasthomas** [comment]
PW being a spa, please use `nuxt generate` or `npm run generate` to build web app.

**Comment by ragouel** [comment]
Fails with the same error.

**Comment by liyasthomas** [comment]
I can't reproduce the issue here at my end. Kindly follow the below steps:
1. Download and extract repo
2. `npm i`
3. `npm run generate`
