### ISSUE TITLE
Nuxt fatal error

### ISSUE THREAD

**Issue by L04DB4L4NC3R** [liyasthomas/postwoman#883]
**Describe the bug**
`npm run build` fails

**To Reproduce**
1. Download the release 
```sh
wget https://github.com/liyasthomas/postwoman/archive/v1.9.7.tar.gz
```
2. Unzip 
```sh
tar -xvf v1.9.7.tar.gz
```
3. `cd` into the created directory and run:

```sh
npm i
```
4. Run build:
```sh
npm run build
```

After running these commands, the installation was supposed to complete successfully but it failed with the following error:

![Screenshot 2020-05-19 13:10:32](https://user-images.githubusercontent.com/30529572/82330292-2cadf000-99d2-11ea-8903-9ff57ee7e37e.png)

Here is the full error log:

```
WARNING in ./node_modules/yargs-parser/index.js 586:21-48
Critical dependency: the request of a dependency is an expression
 @ ./assets/js/curlparser.js
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./pages/index.vue?vue&type=script&lang=js&
 @ ./pages/index.vue?vue&type=script&lang=js&
 @ ./pages/index.vue
 @ ./.nuxt/router.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

ERROR in ./components/layout/footer.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/layout/footer.vue?vue&type=script&lang=js&)
Module not found: Error: Can't resolve '../../.postwoman/version.json' in '/home/angad/Repos/postwoman-1.9.7/components/layout'
 @ ./components/layout/footer.vue?vue&type=script&lang=js& (./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./components/layout/footer.vue?vue&type=script&lang=js&) 77:0-57 86:19-34
 @ ./components/layout/footer.vue?vue&type=script&lang=js&
 @ ./components/layout/footer.vue
 @ ./node_modules/babel-loader/lib??ref--2-0!./node_modules/vue-loader/lib??vue-loader-options!./layouts/default.vue?vue&type=script&lang=js&
 @ ./layouts/default.vue?vue&type=script&lang=js&
 @ ./layouts/default.vue
 @ ./.nuxt/App.js
 @ ./.nuxt/index.js
 @ ./.nuxt/client.js
 @ multi ./.nuxt/client.js

 FATAL  Nuxt build error

  at WebpackBundler.webpackCompile (node_modules/@nuxt/webpack/dist/webpack.js:5351:21)
  at processTicksAndRejections (internal/process/task_queues.js:97:5)
  at async WebpackBundler.build (node_modules/@nuxt/webpack/dist/webpack.js:5300:5)
  at async Builder.build (node_modules/@nuxt/builder/dist/builder.js:5602:5)
  at async Generator.initiate (node_modules/@nuxt/generator/dist/generator.js:70:7)
  at async Generator.generate (node_modules/@nuxt/generator/dist/generator.js:40:5)
  at async Object.run (node_modules/@nuxt/cli/dist/cli-build.js:100:7)
  at async NuxtCommand.run (node_modules/@nuxt/cli/dist/cli-index.js:2759:7)


   ╭─────────────────────────────╮
   │                             │
   │   ✖ Nuxt Fatal Error        │
   │                             │
   │   Error: Nuxt build error   │
   │                             │
   ╰─────────────────────────────╯

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! postwoman@1.9.5 build: `nuxt build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the postwoman@1.9.5 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/angad/.npm/_logs/2020-05-19T13_06_37_649Z-debug.log
```

**Desktop (please complete the following information):**
 - OS: Arch Linux (5.6.13-arch1-1 kernel)
 - Browser: qutebrowser
 - Postwoman version: 1.9.7
 - Npm version: 5.14.5
 - Nodejs version: 14.2.0

**Comment by liyasthomas** [comment]
@L04DB4L4NC3R, issue have been identified. Pushing a permanent fix now. Kindly [download latest zip](https://github.com/liyasthomas/postwoman/archive/master.zip), then unzip and run:
```
npm i
npm run build
```

**Comment by L04DB4L4NC3R** [comment]
> @L04DB4L4NC3R, issue have been identified. Pushing a permanent fix now. Kindly [download latest zip](https://github.com/liyasthomas/postwoman/archive/master.zip), then unzip and run:
> 
> ```
> npm i
> npm run build
> ```

It works. Thanks for the quick reply.
